[package]
name = "EtHlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.19.0"
rust-crypto = "^0.2"
sha1 = "^0.2.0"
rand = "0.3.14"

[lib]
crate_type = ["cdylib"]

