/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI
 * Method:    initall
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JNI_initall
  (JNIEnv *, jclass);

/*
 * Class:     JNI
 * Method:    send
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_JNI_send
  (JNIEnv *, jclass, jlong);

/*
 * Class:     JNI
 * Method:    receive
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_JNI_receive
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
